# .circleci/config.yml
version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: |
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install zip gcc-11 g++-11 cmake # valgrind
      - run:
          name: Environment info
          command: |
            pwd
            uname -a
            lscpu
            cat /proc/cpuinfo
            ls
      - run:
          name: Build and install
          command: |
            mkdir build && mkdir artifacts
            cd build
            CXX=g++-11 CC=gcc-11 cmake ..
            CXX=g++-11 CC=gcc-11 cmake --build . -j6
            CXX=g++-11 CC=gcc-11 cmake --install . --prefix ../artifacts
            cd ..
            zip artifacts artifacts/**/*

      - store_artifacts:
          path: artifacts.zip
          destination: artifacts

workflows:
  build:
    jobs:
      - build-medium:
          filters:
            branches:
              ignore:
                - gh-pages
                - test/sfml